# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the action will run. 
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Setup toolchain
      - name: Install PlatformIO CLI
        run: python3 -c "$(curl -fsSL https://raw.githubusercontent.com/platformio/platformio/master/scripts/get-platformio.py)"

      - name: Install Protobuf-Compiler (NanoPB)
        run: |
          curl -LO https://jpa.kapsi.fi/nanopb/download/nanopb-0.4.4-linux-x86.tar.gz
          tar xvf nanopb-0.4.4-linux-x86.tar.gz -C $HOME/.local

      # Build
      - name: Build
        run: |
          export PATH="$PATH:$HOME/.platformio/penv/bin:$HOME/.local/nanopb-0.4.4-linux-x86/generator-bin"
          pio run
          protoc --version
