# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the action will run. 
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Setup toolchain
      - name: Install PlatformIO CLI
        run: python3 -c "$(curl -fsSL https://raw.githubusercontent.com/platformio/platformio/master/scripts/get-platformio.py)"

      - name: Install Protobuf-Compiler
        run: |
          PB_REL="https://github.com/protocolbuffers/protobuf/releases"
          curl -LO $PB_REL/download/v3.13.0/protoc-3.13.0-linux-x86_64.zip
          unzip protoc-3.13.0-linux-x86_64.zip -d $HOME/.local

      # Build
      - name: Build
        run: |
          export PATH="$PATH:$HOME/.platformio/penv/bin:$HOME/.local/bin"
          pio run
          protoc --version
